version: '3.9'
services:
    app:
        container_name: php8.1
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www

    web:
        container_name: nginx
        build:
            context: ./
            dockerfile: docker/web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www

        ports:
            - 80:80
        depends_on:
            - "app"
