version: '3.9'
services:
    app:
        container_name: php8.1
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www

    web:
        container_name: nginx
        build:
            context: ./
            dockerfile: docker/web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www

        ports:
            - 80:80
        depends_on:
            - "app"

    database:
        image: mariadb:10.6
        container_name: maria_db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 33061:3306

volumes:
    dbdata:
